---
title: "Baseline data simulation"
author: "Beatriz Valcarcel"
date: "2022-04-20"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{baseline data simulation}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r}
library(ggplot2)
library(data.table)
library(magrittr)
library(surveillance)

```

## Simulate baseline with no seasonality and two weekly patterns


```{r}
## sim 1
baseline_1  <- simulate_baseline_data(
                                    start_date = as.Date("2012-01-01"),
                                    end_date = as.Date("2019-12-31"),
                                    seasonal_pattern_n = 1,
                                    weekly_pattern_n = 2,
                                    alpha = 6, 
                                    beta = 0, 
                                    gamma_1 = 0.2, 
                                    gamma_2 = 0.2, 
                                    gamma_3 = 0.5, 
                                    gamma_4 = 0.4, 
                                    phi = 2, 
                                    shift = 29 
                                  )



baseline_1[,s:=1]

## sim 2
baseline_2  <- simulate_baseline_data(
                                    start_date = as.Date("2012-01-01"),
                                    end_date = as.Date("2019-12-31"),
                                    seasonal_pattern_n = 1,
                                    weekly_pattern_n = 2,
                                    alpha = 0.5, 
                                    beta = 0, 
                                    gamma_1 = 1.5, 
                                    gamma_2 = 1.4, 
                                    gamma_3 = 0.5, 
                                    gamma_4 = 0.4, 
                                    phi = 1, 
                                    shift = -167 
                                  )


baseline_2[,s:=2]


## sim 3
baseline_3  <- simulate_baseline_data(
                                    start_date = as.Date("2012-01-01"),
                                    end_date = as.Date("2019-12-31"),
                                    seasonal_pattern_n = 0,
                                    weekly_pattern_n = 2,
                                    alpha = 5.5, 
                                    beta = 0, 
                                    gamma_1 = 0, 
                                    gamma_2 = 0, 
                                    gamma_3 = 0.3, 
                                    gamma_4 = 0.25, 
                                    phi = 1, 
                                    shift = 1
                                  )

baseline_3[,s:=3]


## sim 4
baseline_4 <- simulate_baseline_data(
                                    start_date = as.Date("2012-01-01"),
                                    end_date = as.Date("2019-12-31"),
                                    seasonal_pattern_n = 0,
                                    weekly_pattern_n = 2,
                                    alpha = 0, 
                                    beta = 0, 
                                    gamma_1 = 0, 
                                    gamma_2 = 0, 
                                    gamma_3 = 0.3,
                                    gamma_4 = 0.25, 
                                    phi = 1, 
                                    shift = 1
                                  )

baseline_4[,s:=4]

## sim 5
baseline_5 <- simulate_baseline_data(
                                    start_date = as.Date("2012-01-01"),
                                    end_date = as.Date("2019-12-31"),
                                    seasonal_pattern_n = 1,
                                    weekly_pattern_n = 2,
                                    alpha = 6, 
                                    beta = 0, 
                                    gamma_1 = 0.3, 
                                    gamma_2 = 2, 
                                    gamma_3 = 0.3, 
                                    gamma_4 = 0.5, 
                                    phi = 1.5, 
                                    shift = -50 
                                  )

baseline_5[,s:=5]


## sim 6
baseline_6 <- simulate_baseline_data(
                                    start_date = as.Date("2012-01-01"),
                                    end_date = as.Date("2019-12-31"),
                                    seasonal_pattern_n = 1,
                                    weekly_pattern_n = 1,
                                    alpha = 1, 
                                    beta = 0, 
                                    gamma_1 = 0.1, 
                                    gamma_2 = 2, 
                                    gamma_3 = 0.05, 
                                    gamma_4 = 0.05, 
                                    phi = 1, 
                                    shift = -50 
                                  )

baseline_6[,s:=6]


## sim 7
baseline_7 <- simulate_baseline_data(
                                    start_date = as.Date("2012-01-01"),
                                    end_date = as.Date("2019-12-31"),
                                    seasonal_pattern_n = 0,
                                    weekly_pattern_n = 1,
                                    alpha = 6, 
                                    beta = 0.0001, 
                                    gamma_1 = 0, 
                                    gamma_2 = 0, 
                                    gamma_3 = 0.6, 
                                    gamma_4 = 0.9, 
                                    phi = 1.5, 
                                    shift = 0 
                                  )


baseline_7[,s:=7]

## sim 8
baseline_8 <- simulate_baseline_data(
                                    start_date = as.Date("2012-01-01"),
                                    end_date = as.Date("2019-12-31"),
                                    seasonal_pattern_n = 1,
                                    weekly_pattern_n = 1,
                                    alpha = 3, 
                                    beta = 0, 
                                    gamma_1 = 1.5,
                                    gamma_2 = 0.1, 
                                    gamma_3 = 0.2, 
                                    gamma_4 = 0.3, 
                                    phi = 1, 
                                    shift = -150 )



baseline_8[,s:=8]

## sim 9
baseline_9 <- simulate_baseline_data(
                                    start_date = as.Date("2012-01-01"),
                                    end_date = as.Date("2019-12-31"),
                                    seasonal_pattern_n = 1,
                                    weekly_pattern_n = 1,
                                    alpha = 3, 
                                    beta = 0, 
                                    gamma_1 = 0.2, 
                                    gamma_2 = 0.1, 
                                    gamma_3 = 0.05, 
                                    gamma_4 = 0.15, 
                                    phi = 1, 
                                    shift = -200 
                                  )

baseline_9[,s:=9]

## sim 10

baseline_10 <- simulate_baseline_data(
                                    start_date = as.Date("2012-01-01"),
                                    end_date = as.Date("2019-12-31"),
                                    seasonal_pattern_n = 1,
                                    weekly_pattern_n = 1,
                                    alpha = 5, 
                                    beta = 0, 
                                    gamma_1 = 0.2, 
                                    gamma_2 = 0.1, 
                                    gamma_3 = 0.05, 
                                    gamma_4 = 0.1, 
                                    phi = 1, 
                                    shift = 0 
                                  )


baseline_10[,s:=10]

## sim 11

baseline_11 <- simulate_baseline_data(
                                    start_date = as.Date("2012-01-01"),
                                    end_date = as.Date("2019-12-31"),
                                    seasonal_pattern_n = 2,
                                    weekly_pattern_n = 1,
                                    alpha = 0.5, 
                                    beta = 0, 
                                    gamma_1 = 0.4, 
                                    gamma_2 = 0, 
                                    gamma_3 = 0.05, 
                                    gamma_4 = 0.15, 
                                    phi = 1, 
                                    shift = 0 
                                  )

baseline_11[,s:=11]

## sim 12

baseline_12 <- simulate_baseline_data(
                                    start_date = as.Date("2012-01-01"),
                                    end_date = as.Date("2019-12-31"),
                                    seasonal_pattern_n = 2,
                                    weekly_pattern_n = 1,
                                    alpha = 9, 
                                    beta = 0, 
                                    gamma_1 = 0.5, 
                                    gamma_2 = 0.2, 
                                    gamma_3 = 0.2, 
                                    gamma_4 = 0.4, 
                                    phi = 4, 
                                    shift = 57
                                  )


baseline_12[,s:=12]


## sim 13

baseline_13 <- simulate_baseline_data(
                                    start_date = as.Date("2012-01-01"),
                                    end_date = as.Date("2019-12-31"),
                                    seasonal_pattern_n = 2,
                                    weekly_pattern_n = 1,
                                    alpha = 2,
                                    beta = 0.0005, 
                                    gamma_1 = 0.8, 
                                    gamma_2 = 0.8, 
                                    gamma_3 = 0.8, 
                                    gamma_4 = 0.4, 
                                    phi = 4, 
                                    shift = 57 
                                  )

baseline_13[,s:=13]


## sim 14

baseline_14 <- simulate_baseline_data(
                                    start_date = as.Date("2012-01-01"),
                                    end_date = as.Date("2019-12-31"),
                                    seasonal_pattern_n = 1,
                                    weekly_pattern_n = 4,
                                    alpha = 0.05, 
                                    beta = 0, 
                                    gamma_1 = 0.01, 
                                    gamma_2 = 0.01, 
                                    gamma_3 = 1.8, 
                                    gamma_4 = 0.1, 
                                    phi = 1, 
                                    shift = -85 
                                  )

baseline_14[,s:=14]

## sim 15

baseline_15 <- simulate_baseline_data(
                                    start_date = as.Date("2012-01-01"),
                                    end_date = as.Date("2019-12-31"),
                                    seasonal_pattern_n = 1,
                                    weekly_pattern_n = 2,
                                    alpha = 3, 
                                    beta = 0, 
                                    gamma_1 = 0.8, 
                                    gamma_2 = 0.6, 
                                    gamma_3 = 0.8, 
                                    gamma_4 = 0.4, 
                                    phi = 4, 
                                    shift = 29)

baseline_15[,s:=15]


## sim 16

baseline_16 <- simulate_baseline_data(
                                    start_date = as.Date("2012-01-01"),
                                    end_date = as.Date("2019-12-31"),
                                    seasonal_pattern_n = 0,
                                    weekly_pattern_n = 2,
                                    alpha = 6, 
                                    beta = 0, 
                                    gamma_1 = 0, 
                                    gamma_2 = 0, 
                                    gamma_3 = 0.8, 
                                    gamma_4 = 0.4, 
                                    phi = 4, 
                                    shift = 1
                                  )
                                   

baseline_16[,s:=16]

baseline <- rbind(baseline_1,
                  baseline_2,
                  baseline_3,
                  baseline_4,
                  baseline_5,
                  baseline_6,
                  baseline_7,
                  baseline_8,
                  baseline_9,
                  baseline_10,
                  baseline_11,
                  baseline_12,
                  baseline_13,
                  baseline_14,
                  baseline_15,
                  baseline_16)



q <- ggplot(baseline, aes(x = date, y = n))
q <- q + geom_line(lwd = 1)
q <- q + facet_wrap(~s, scales = "free")
q <- q + splstyle::scale_fill_fhi(palette = "contrast")
q <- q + splstyle::theme_fhi_lines_horizontal(legend_position = "bottom")
q


q <- ggplot(baseline, aes(wday, n, group=wday))
q <- q + facet_wrap(~s, scales = "free")
q <- q + geom_boxplot()
q

q <- ggplot(baseline, aes(wday, n, group=calmonth))
q <- q + facet_wrap(~s, scales = "free")
q <- q + geom_boxplot()
q

```


## Simulation of baseline data 

```{r}


baseline <- simulate_baseline_data( 
                                    start_date = as.Date("2012-01-01"),
                                    end_date = as.Date("2019-12-31"),
                                    seasonal_pattern_n = 1,
                                    weekly_pattern_n = 2,
                                    alpha = 3, 
                                    beta = 0, 
                                    gamma_1 = 0.8, 
                                    gamma_2 = 0.6, 
                                    gamma_3 = 0.8, 
                                    gamma_4 = 0.4, 
                                    phi = 2, 
                                    shift_1 = 6
                                  )
baseline[,s:=15]

q <- ggplot(baseline, aes(x = date, y = n))
q <- q + geom_line(lwd = 1)
q <- q + facet_wrap(~s, scales = "free")
q <- q + splstyle::scale_fill_fhi(palette = "contrast")
q <- q + splstyle::theme_fhi_lines_horizontal(legend_position = "bottom")
q


# q <- ggplot(baseline, aes(wday, n, group=wday))
# q <- q + facet_wrap(~s, scales = "free")
# q <- q + geom_boxplot()
# q
# 
# q <- ggplot(baseline, aes(wday, n, group=calmonth))
# q <- q + facet_wrap(~s, scales = "free")
# q <- q + geom_boxplot()
# q

```

## Add seasonal outbreaks 

```{r}


baseline_with_seasonal <- simulate_seasonal_outbreak_data (baseline,
                                                           week_season_start = 40,
                                                           week_season_peak = 4,
                                                           week_season_end = 20,
                                                           n_season_outbreak = 1,
                                                           m = 150)



q <- ggplot(baseline_with_seasonal, aes(x = date, y = n))
q <- q + geom_line(colour = "red")
q <- q + geom_line(data=baseline_with_seasonal, aes(x = date, y = n - seasonal_outbreak_n_rw ))
q <- q + facet_wrap(~s, scales = "free")
q <- q + splstyle::scale_fill_fhi(palette = "contrast")
q <- q + splstyle::theme_fhi_lines_horizontal(legend_position = "bottom")
q



```


## Add spikeoutbreak 

```{r}
baseline_with_seasonal_spike  <- simulate_spike_outbreak_data(baseline_with_seasonal,
                                                              n_sp_outbreak=1,
                                                              m = 15)
                                                      

q <- ggplot(baseline_with_seasonal_spike, aes(x = date, y = n))
q <- q + geom_line(colour = "green")
q <- q + geom_line(data=baseline_with_seasonal, aes(x = date, y = n),colour = "red")
q <- q + geom_line(data=baseline, aes(x = date, y = n))
q <- q + splstyle::scale_fill_fhi(palette = "contrast")
q <- q + splstyle::theme_fhi_lines_horizontal(legend_position = "bottom")
q


```

## Add holiday effect 

```{r}


baseline_with_seasonal_spike_holiday  <- add_holiday_effect( baseline_with_seasonal_spike,
                                                              holiday_data= fhidata::norway_dates_holidays,
                                                              holiday_effect=0.5)

test <- baseline_with_seasonal_spike_holiday[isoyear %in% 2019]

q <- ggplot(test, aes(x = date, y = n))
q <- q + geom_line(colour = "yellow")
q <- q + geom_line(data=baseline_with_seasonal_spike, aes(x = date, y = n),colour = "green")
q <- q + geom_line(data=baseline_with_seasonal, aes(x = date, y = n),colour = "red")
q <- q + geom_line(data=baseline, aes(x = date, y = n))
q <- q + splstyle::scale_fill_fhi(palette = "contrast")
q <- q + splstyle::theme_fhi_lines_horizontal(legend_position = "bottom")
q


```



## Test Quasipoisson Ccore skuhr

```{r}


quasipoisson_alerts  <- quasipoisson_core_skuhr_create_alerts( baseline_with_seasonal_spike_holiday,
                                                                                reweights = 1,
                                                                                remove.highcounts = 0,
                                                                                is_day = T)



q <- ggplot(quasipoisson_alerts, aes(x = date, y = n_tot),color = as.factor(group)))
q <- q + geom_line()
q <- q + geom_point(quasipoisson_alerts,aes(x = date, y = n_tot))

q <- q + splstyle::scale_fill_fhi(palette = "contrast")
q <- q + splstyle::theme_fhi_lines_horizontal(legend_position = "bottom")
q


```


